const ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  HR: 'HR',
  ADMIN: 'ADMIN',
  DEFAULT_ADMIN: 'DEFAULT_ADMIN',
});

const ADMIN_PANEL_ROLES = [ROLES.STAFF, ROLES.HR, ROLES.ADMIN, ROLES.DEFAULT_ADMIN];

const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  COMPLETED: 'COMPLETED',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

const PAYMENT_TYPES = Object.freeze({
  COD: 'COD',
  QR: 'QR',
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = {
  ROLES,
  ADMIN_PANEL_ROLES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_TYPES,
  ERROR_CODES,
};
